DROP TABLE CLIENTESATENDIDOS;
CREATE TABLE CLIENTESATENDIDOS(
TICKET integer CONSTRAINT CLIENTESATENDIDOS_pk PRIMARY KEY,
EDAD VARCHAR2(40)
);

DROP TABLE CLIENTESNOATENDIDOS;
CREATE TABLE CLIENTESNOATENDIDOS(
TICKET integer CONSTRAINT CLIENTESNOATENDIDOS_pk PRIMARY KEY,
EDAD VARCHAR2(40)
);

select * from CLIENTESATENDIDOS;

select * from CLIENTESNOATENDIDOS;

delete from CLIENTESATENDIDOS; 
delete from CLIENTESNOATENDIDOS;